/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Share } from "./Share";
import { ShareCountArgs } from "./ShareCountArgs";
import { ShareFindManyArgs } from "./ShareFindManyArgs";
import { ShareFindUniqueArgs } from "./ShareFindUniqueArgs";
import { CreateShareArgs } from "./CreateShareArgs";
import { UpdateShareArgs } from "./UpdateShareArgs";
import { DeleteShareArgs } from "./DeleteShareArgs";
import { PortfolioFindManyArgs } from "../../portfolio/base/PortfolioFindManyArgs";
import { Portfolio } from "../../portfolio/base/Portfolio";
import { TransactionFindManyArgs } from "../../transaction/base/TransactionFindManyArgs";
import { Transaction } from "../../transaction/base/Transaction";
import { ShareService } from "../share.service";
@graphql.Resolver(() => Share)
export class ShareResolverBase {
  constructor(protected readonly service: ShareService) {}

  async _sharesMeta(
    @graphql.Args() args: ShareCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Share])
  async shares(@graphql.Args() args: ShareFindManyArgs): Promise<Share[]> {
    return this.service.shares(args);
  }

  @graphql.Query(() => Share, { nullable: true })
  async share(
    @graphql.Args() args: ShareFindUniqueArgs
  ): Promise<Share | null> {
    const result = await this.service.share(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Share)
  async createShare(@graphql.Args() args: CreateShareArgs): Promise<Share> {
    return await this.service.createShare({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Share)
  async updateShare(
    @graphql.Args() args: UpdateShareArgs
  ): Promise<Share | null> {
    try {
      return await this.service.updateShare({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Share)
  async deleteShare(
    @graphql.Args() args: DeleteShareArgs
  ): Promise<Share | null> {
    try {
      return await this.service.deleteShare(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Portfolio], { name: "portfolios" })
  async findPortfolios(
    @graphql.Parent() parent: Share,
    @graphql.Args() args: PortfolioFindManyArgs
  ): Promise<Portfolio[]> {
    const results = await this.service.findPortfolios(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Transaction], { name: "transactions" })
  async findTransactions(
    @graphql.Parent() parent: Share,
    @graphql.Args() args: TransactionFindManyArgs
  ): Promise<Transaction[]> {
    const results = await this.service.findTransactions(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
